In [1]:
import pandas as pd
from pymongo import MongoClient
import os
from dotenv import load_dotenv
load_dotenv()

True

In [2]:
url = os.getenv("url")

In [3]:
url

'mongodb+srv://admin:admin@bcn.e0wqq.mongodb.net/test'

In [4]:
client = MongoClient(url)

In [5]:
client

MongoClient(host=['bcn-shard-00-00.e0wqq.mongodb.net:27017', 'bcn-shard-00-01.e0wqq.mongodb.net:27017', 'bcn-shard-00-02.e0wqq.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-lbgrvb-shard-0', tls=True)

In [6]:
db = client.get_database("BCN")

In [7]:
db

Database(MongoClient(host=['bcn-shard-00-00.e0wqq.mongodb.net:27017', 'bcn-shard-00-01.e0wqq.mongodb.net:27017', 'bcn-shard-00-02.e0wqq.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, authsource='admin', replicaset='atlas-lbgrvb-shard-0', tls=True), 'BCN')

In [8]:
inm_nat= list(db["INM.NATIONALITY"].find({}))
data_inm_nat= pd.DataFrame(data = inm_nat)

In [9]:
data_inm_nat

,_id,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Nationality,Number
0,628d907528360e0bbf01e184,2017,1,Ciutat Vella,1,el Raval,Spain,1109
1,628d907528360e0bbf01e185,2017,1,Ciutat Vella,2,el Barri Gòtic,Spain,482
2,628d907528360e0bbf01e186,2017,1,Ciutat Vella,3,la Barceloneta,Spain,414
3,628d907528360e0bbf01e187,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Spain,537
4,628d907528360e0bbf01e188,2017,2,Eixample,5,el Fort Pienc,Spain,663
...,...,...,...,...,...,...,...,...
35219,628d908d28360e0bbf026b17,2015,10,Sant Martí,70,el Besòs i el Maresme,No information,0
35220,628d908d28360e0bbf026b18,2015,10,Sant Martí,71,Provençals del Poblenou,No information,0
35221,628d908d28360e0bbf026b19,2015,10,Sant Martí,72,Sant Martí de Provençals,No information,0
35222,628d908d28360e0bbf026b1a,2015,10,Sant Martí,73,la Verneda i la Pau,No information,1
35223,628d908d28360e0bbf026b1b,2015,99,No consta,99,No consta,No information,0

In [10]:
data_inm_nat.head(20)

,_id,Year,District Code,District Name,Neighborhood Code,Neighborhood Name,Nationality,Number
0,628d907528360e0bbf01e184,2017,1,Ciutat Vella,1,el Raval,Spain,1109
1,628d907528360e0bbf01e185,2017,1,Ciutat Vella,2,el Barri Gòtic,Spain,482
2,628d907528360e0bbf01e186,2017,1,Ciutat Vella,3,la Barceloneta,Spain,414
3,628d907528360e0bbf01e187,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Spain,537
4,628d907528360e0bbf01e188,2017,2,Eixample,5,el Fort Pienc,Spain,663
5,628d907528360e0bbf01e189,2017,2,Eixample,6,la Sagrada Família,Spain,1181
6,628d907528360e0bbf01e18a,2017,2,Eixample,7,la Dreta de l'Eixample,Spain,1063
7,628d907528360e0bbf01e18b,2017,2,Eixample,8,l'Antiga Esquerra de l'Eixample,Spain,1177
8,628d907528360e0bbf01e18c,2017,2,Eixample,9,la Nova Esquerra de l'Eixample,Spain,1593
9,628d907528360e0bbf01e18d,2017,2,Eixample,10,Sant Antoni,Spain,883
10,628d907528360e0bbf01e18e,2017,3,Sants-Montjuïc,11,el Poble Sec,Spain,826
11,628d907528360e0bbf01e18f,2017,3,Sants-Montjuïc,12,la Marina del Prat Vermell,Spain,23
12,628d907528360e0bbf01e190,2017,3,Sants-Montjuïc,13,la Marina de Port,Spain,574
13,628d907528360e0bbf01e191,2017,3,Sants-Montjuïc,14,la Font de la Guatlla,Spain,264
14,628d907528360e0bbf01e192,2017,3,Sants-Montjuïc,15,Hostafrancs,Spain,410
15,628d907528360e0bbf01e193,2017,3,Sants-Montjuïc,16,la Bordeta,Spain,434
16,628d907528360e0bbf01e194,2017,3,Sants-Montjuïc,17,Sants - Badal,Spain,605
17,628d907528360e0bbf01e195,2017,3,Sants-Montjuïc,18,Sants,Spain,1083
18,628d907528360e0bbf01e196,2017,4,Les Corts,19,les Corts,Spain,1027
19,628d907528360e0bbf01e197,2017,4,Les Corts,20,la Maternitat i Sant Ramon,Spain,630

In [11]:
print(data_inm_nat['Nationality'].unique())

['Spain' 'Italy' 'China' 'Colombia' 'Venezuela' 'Pakistan' 'Honduras'
 'France' 'Peru' 'Morocco' 'Argentina' 'Brasil' 'United States'
 'United Kingdom' 'India' 'Ecuador' 'Russia' 'Germany'
 'Dominican Republic' 'Mexico' 'Romania' 'Chile' 'Bolivia' 'Portugal'
 'Ukraine' 'Bangladesh' 'Philippines' 'Paraguay' 'Georgia' 'Netherlands'
 'Cuba' 'Poland' 'El Salvador' 'Turkey' 'Iran' 'Japan' 'Uruguay' 'Sweden'
 'Nepal' 'Armenia' 'Belgium' 'Bulgaria' 'Algeria' 'South Korea'
 'Nicaragua' 'Canada' 'Senegal' 'Switzerland' 'Greece' 'Ireland'
 'Costa Rica' 'Hungary' 'Egypt' 'Panama' 'Lebanon' 'Nigeria' 'Guatemala'
 'Israel' 'Austria' 'Denmark' 'Finland' 'Kazakhstan' 'Lithuania' 'Syria'
 'Vietnam' 'Albania' 'Belarus' 'Australia' 'Czech Republic' 'Croatia'
 'Equatorial Guinea' 'Serbia' 'Slovakia' 'Norway' 'Tunisia' 'Ghana'
 'Latvia' 'Moldova' 'Andorra' 'South Africa' 'Slovenia' 'Gambia' 'Camerun'
 'Indonesia' 'Jordan' 'Azerbaijan' 'Estonia' 'Guinea' 'Iraq'
 'Saudi Arabia' 'State of Palestine' 'Uzbekistan' 'Cyprus' 'Iceland'
 'Libya' 'Thailand' 'Mali' 'New Zealand' 'Afghanistan' 'Macedonia'
 'Angola' 'Ivory Coast' 'Kenya' 'Malaysia' 'Mongolia'
 'Bosnia and Herzegovina' 'Singapore' 'Luxembourg' 'Sudan' 'Guinea-Bissau'
 'Tanzania' 'Dominica' 'Kyrgyzstan' 'Congo' 'Mauritania' 'Malta' 'Kuwait'
 'Montenegro' 'Mozambique' 'Uganda' 'Benin' 'Haiti' 'Trinidad and Tobago'
 'Myanmar' 'Ethiopia' 'Mauritius' 'Namibia' 'Sierra Leone' 'Qatar'
 'Sri Lanka' 'Burkina Faso' 'Malawi' 'Togo' 'Eritrea'
 'United Arab Emirates' 'Cambodja' 'Turkmenistan' 'Chad' 'Zimbabwe'
 'Botswana' 'Gabon' 'Madagascar' 'Niger' 'Somalia' 'Zambia' 'The Bahamas'
 'Jamaica' 'Yemen' 'Cape Verde' 'São Tomé and Príncipe'
 'Antigua and Barbuda' 'Barbados' 'Grenada' 'Bahrain' 'Laos' 'Maldives'
 'Oman' 'Solomon Islands' 'No information' 'Burundi'
 'Central African Republic' 'North Korea' 'Guyana' 'Lesotho' 'Liberia'
 'Puerto Rico' 'Rwanda' 'Saint Kitts and Nevis' 'San Marino' 'Seychelles'
 'Suriname' 'Tajikistan' 'East Timor' 'Palestinian territories' 'Djibouti'
 'Swaziland' 'Taiwan']

In [12]:
data_inm_nat = data_inm_nat.drop(columns=["_id","Neighborhood Code","Neighborhood Name"])

In [13]:
data_inm_nat.isnull().sum()

Year             0
District Code    0
District Name    0
Nationality      0
Number           0
dtype: int64

In [14]:
type(data_inm_nat["Nationality"])

pandas.core.series.Series

In [15]:
data_inm_nat["Nationality"]=="No information"

0        False
1        False
2        False
3        False
4        False
         ...
35219     True
35220     True
35221     True
35222     True
35223     True
Name: Nationality, Length: 35224, dtype: bool

In [16]:
data_inm_nat[data_inm_nat["Nationality"]=="No information"]

       Year District Code District Name     Nationality  Number
11692  2017             1  Ciutat Vella  No information       2
11693  2017             1  Ciutat Vella  No information       1
11694  2017             1  Ciutat Vella  No information       0
11695  2017             1  Ciutat Vella  No information       0
11696  2017             2      Eixample  No information       2
...     ...           ...           ...             ...     ...
35219  2015            10    Sant Martí  No information       0
35220  2015            10    Sant Martí  No information       0
35221  2015            10    Sant Martí  No information       0
35222  2015            10    Sant Martí  No information       1
35223  2015            99     No consta  No information       0

[222 rows x 5 columns]

In [17]:
data_inm_nat.drop(data_inm_nat[data_inm_nat["Nationality"]=="No information"].index, inplace=True)

In [18]:
data_inm_nat[data_inm_nat["District Name"]=="No consta"]

       Year District Code District Name          Nationality  Number
73     2017            99     No consta                Spain       2
147    2017            99     No consta                Italy       0
221    2017            99     No consta                China       0
295    2017            99     No consta             Colombia       0
369    2017            99     No consta            Venezuela       0
...     ...           ...           ...                  ...     ...
34853  2015            99     No consta           Seychelles       0
34927  2015            99     No consta         Sierra Leone       0
35001  2015            99     No consta            Swaziland       0
35075  2015            99     No consta               Taiwan       0
35149  2015            99     No consta  Trinidad and Tobago       0

[473 rows x 5 columns]

In [19]:
data_inm_nat.drop(data_inm_nat[data_inm_nat["District Name"]=="No consta"].index, inplace=True)

In [20]:
data_inm_nat

       Year District Code District Name          Nationality  Number
0      2017             1  Ciutat Vella                Spain    1109
1      2017             1  Ciutat Vella                Spain     482
2      2017             1  Ciutat Vella                Spain     414
3      2017             1  Ciutat Vella                Spain     537
4      2017             2      Eixample                Spain     663
...     ...           ...           ...                  ...     ...
35144  2015            10    Sant Martí  Trinidad and Tobago       0
35145  2015            10    Sant Martí  Trinidad and Tobago       0
35146  2015            10    Sant Martí  Trinidad and Tobago       0
35147  2015            10    Sant Martí  Trinidad and Tobago       0
35148  2015            10    Sant Martí  Trinidad and Tobago       0

[34529 rows x 5 columns]

In [21]:
df_new = data_inm_nat.groupby(by=["Year","District Code","District Name","Nationality"],as_index=False)["Number"].sum()
df_new

      Year District Code District Name  Nationality  Number
0     2015             1  Ciutat Vella  Afghanistan       3
1     2015             1  Ciutat Vella      Albania      13
2     2015             1  Ciutat Vella      Algeria      75
3     2015             1  Ciutat Vella      Andorra       1
4     2015             1  Ciutat Vella       Angola       0
...    ...           ...           ...          ...     ...
4725  2017             9   Sant Andreu    Venezuela     192
4726  2017             9   Sant Andreu      Vietnam       5
4727  2017             9   Sant Andreu        Yemen       0
4728  2017             9   Sant Andreu       Zambia       0
4729  2017             9   Sant Andreu     Zimbabwe       0

[4730 rows x 5 columns]

In [22]:
df_new[df_new["Nationality"]=="Spain"]

      Year District Code        District Name Nationality  Number
128   2015             1         Ciutat Vella       Spain    2827
281   2015            10           Sant Martí       Spain    4913
434   2015             2             Eixample       Spain    6894
587   2015             3       Sants-Montjuïc       Spain    4747
740   2015             4            Les Corts       Spain    2204
893   2015             5  Sarrià-Sant Gervasi       Spain    3796
1046  2015             6               Gràcia       Spain    3092
1199  2015             7       Horta-Guinardó       Spain    3429
1352  2015             8           Nou Barris       Spain    3143
1505  2015             9          Sant Andreu       Spain    2978
1662  2016             1         Ciutat Vella       Spain    2413
1824  2016            10           Sant Martí       Spain    4295
1986  2016             2             Eixample       Spain    6013
2148  2016             3       Sants-Montjuïc       Spain    4071
2310  2016             4            Les Corts       Spain    1961
2472  2016             5  Sarrià-Sant Gervasi       Spain    3248
2634  2016             6               Gràcia       Spain    2621
2796  2016             7       Horta-Guinardó       Spain    3033
2958  2016             8           Nou Barris       Spain    2880
3120  2016             9          Sant Andreu       Spain    2508
3280  2017             1         Ciutat Vella       Spain    2542
3438  2017            10           Sant Martí       Spain    4726
3596  2017             2             Eixample       Spain    6560
3754  2017             3       Sants-Montjuïc       Spain    4219
3912  2017             4            Les Corts       Spain    1955
4070  2017             5  Sarrià-Sant Gervasi       Spain    3425
4228  2017             6               Gràcia       Spain    2944
4386  2017             7       Horta-Guinardó       Spain    3255
4544  2017             8           Nou Barris       Spain    3013
4702  2017             9          Sant Andreu       Spain    2713

In [23]:
df_new.iloc[2]

Year                     2015
District Code               1
District Name    Ciutat Vella
Nationality           Algeria
Number                     75
Name: 2, dtype: object

In [24]:
df_new.head()

   Year District Code District Name  Nationality  Number
0  2015             1  Ciutat Vella  Afghanistan       3
1  2015             1  Ciutat Vella      Albania      13
2  2015             1  Ciutat Vella      Algeria      75
3  2015             1  Ciutat Vella      Andorra       1
4  2015             1  Ciutat Vella       Angola       0

In [25]:
import numpy as np

df_new['id'] = np.arange(df_new.shape[0])

In [26]:
df_new

      Year District Code District Name  Nationality  Number    id
0     2015             1  Ciutat Vella  Afghanistan       3     0
1     2015             1  Ciutat Vella      Albania      13     1
2     2015             1  Ciutat Vella      Algeria      75     2
3     2015             1  Ciutat Vella      Andorra       1     3
4     2015             1  Ciutat Vella       Angola       0     4
...    ...           ...           ...          ...     ...   ...
4725  2017             9   Sant Andreu    Venezuela     192  4725
4726  2017             9   Sant Andreu      Vietnam       5  4726
4727  2017             9   Sant Andreu        Yemen       0  4727
4728  2017             9   Sant Andreu       Zambia       0  4728
4729  2017             9   Sant Andreu     Zimbabwe       0  4729

[4730 rows x 6 columns]

In [34]:
df_new

      Year District Code District Name  Nationality  Number    id
0     2015             1  Ciutat Vella  Afghanistan       3     0
1     2015             1  Ciutat Vella      Albania      13     1
2     2015             1  Ciutat Vella      Algeria      75     2
3     2015             1  Ciutat Vella      Andorra       1     3
4     2015             1  Ciutat Vella       Angola       0     4
...    ...           ...           ...          ...     ...   ...
4725  2017             9   Sant Andreu    Venezuela     192  4725
4726  2017             9   Sant Andreu      Vietnam       5  4726
4727  2017             9   Sant Andreu        Yemen       0  4727
4728  2017             9   Sant Andreu       Zambia       0  4728
4729  2017             9   Sant Andreu     Zimbabwe       0  4729

[4730 rows x 6 columns]

In [30]:
inm_nat= db["INM.NATION"]

In [31]:
inm_nat_clean = df_new.to_dict('records')

In [32]:
inm_nat_clean

[{'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Afghanistan',
  'Number': 3,
  'id': 0},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Albania',
  'Number': 13,
  'id': 1},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Algeria',
  'Number': 75,
  'id': 2},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Andorra',
  'Number': 1,
  'id': 3},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Angola',
  'Number': 0,
  'id': 4},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Argentina',
  'Number': 185,
  'id': 5},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Armenia',
  'Number': 7,
  'id': 6},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Australia',
  'Number': 32,
  'id': 7},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Austria',
  'Number': 21,
  'id': 8},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Azerbaijan',
  'Number': 13,
  'id': 9},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Bahrain',
  'Number': 0,
  'id': 10},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Bangladesh',
  'Number': 427,
  'id': 11},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Barbados',
  'Number': 0,
  'id': 12},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Belarus',
  'Number': 12,
  'id': 13},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Belgium',
  'Number': 76,
  'id': 14},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Benin',
  'Number': 1,
  'id': 15},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Bolivia',
  'Number': 64,
  'id': 16},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Bosnia and Herzegovina',
  'Number': 1,
  'id': 17},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Brasil',
  'Number': 198,
  'id': 18},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Bulgaria',
  'Number': 46,
  'id': 19},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Burkina Faso',
  'Number': 0,
  'id': 20},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Burundi',
  'Number': 0,
  'id': 21},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Cambodja',
  'Number': 0,
  'id': 22},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Camerun',
  'Number': 5,
  'id': 23},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Canada',
  'Number': 32,
  'id': 24},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Cape Verde',
  'Number': 1,
  'id': 25},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Central African Republic',
  'Number': 0,
  'id': 26},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Chile',
  'Number': 107,
  'id': 27},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'China',
  'Number': 161,
  'id': 28},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Colombia',
  'Number': 185,
  'id': 29},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Congo',
  'Number': 0,
  'id': 30},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Costa Rica',
  'Number': 19,
  'id': 31},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Croatia',
  'Number': 10,
  'id': 32},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Cuba',
  'Number': 39,
  'id': 33},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Cyprus',
  'Number': 5,
  'id': 34},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Czech Republic',
  'Number': 22,
  'id': 35},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Denmark',
  'Number': 38,
  'id': 36},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Djibouti',
  'Number': 0,
  'id': 37},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Dominica',
  'Number': 1,
  'id': 38},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Dominican Republic',
  'Number': 78,
  'id': 39},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ecuador',
  'Number': 106,
  'id': 40},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Egypt',
  'Number': 26,
  'id': 41},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'El Salvador',
  'Number': 13,
  'id': 42},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Equatorial Guinea',
  'Number': 5,
  'id': 43},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Estonia',
  'Number': 8,
  'id': 44},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ethiopia',
  'Number': 0,
  'id': 45},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Finland',
  'Number': 31,
  'id': 46},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'France',
  'Number': 439,
  'id': 47},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Gabon',
  'Number': 0,
  'id': 48},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Gambia',
  'Number': 11,
  'id': 49},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Georgia',
  'Number': 28,
  'id': 50},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Germany',
  'Number': 241,
  'id': 51},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ghana',
  'Number': 8,
  'id': 52},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Greece',
  'Number': 38,
  'id': 53},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Grenada',
  'Number': 0,
  'id': 54},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Guatemala',
  'Number': 12,
  'id': 55},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Guinea',
  'Number': 8,
  'id': 56},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Guinea-Bissau',
  'Number': 0,
  'id': 57},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Haiti',
  'Number': 1,
  'id': 58},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Honduras',
  'Number': 66,
  'id': 59},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Hungary',
  'Number': 39,
  'id': 60},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Iceland',
  'Number': 7,
  'id': 61},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'India',
  'Number': 359,
  'id': 62},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Indonesia',
  'Number': 2,
  'id': 63},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Iran',
  'Number': 13,
  'id': 64},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Iraq',
  'Number': 4,
  'id': 65},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ireland',
  'Number': 41,
  'id': 66},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Israel',
  'Number': 23,
  'id': 67},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Italy',
  'Number': 1080,
  'id': 68},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ivory Coast',
  'Number': 2,
  'id': 69},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Jamaica',
  'Number': 0,
  'id': 70},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Japan',
  'Number': 21,
  'id': 71},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Jordan',
  'Number': 1,
  'id': 72},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Kazakhstan',
  'Number': 14,
  'id': 73},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Kenya',
  'Number': 0,
  'id': 74},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Kuwait',
  'Number': 1,
  'id': 75},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Kyrgyzstan',
  'Number': 0,
  'id': 76},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Latvia',
  'Number': 15,
  'id': 77},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Lebanon',
  'Number': 15,
  'id': 78},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Libya',
  'Number': 8,
  'id': 79},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Lithuania',
  'Number': 17,
  'id': 80},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Luxembourg',
  'Number': 0,
  'id': 81},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Macedonia',
  'Number': 4,
  'id': 82},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Madagascar',
  'Number': 0,
  'id': 83},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Malaysia',
  'Number': 1,
  'id': 84},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Maldives',
  'Number': 0,
  'id': 85},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mali',
  'Number': 3,
  'id': 86},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Malta',
  'Number': 3,
  'id': 87},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mauritania',
  'Number': 11,
  'id': 88},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mauritius',
  'Number': 0,
  'id': 89},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mexico',
  'Number': 185,
  'id': 90},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Moldova',
  'Number': 3,
  'id': 91},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mongolia',
  'Number': 1,
  'id': 92},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Montenegro',
  'Number': 2,
  'id': 93},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Morocco',
  'Number': 400,
  'id': 94},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Mozambique',
  'Number': 0,
  'id': 95},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Namibia',
  'Number': 1,
  'id': 96},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Nepal',
  'Number': 33,
  'id': 97},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Netherlands',
  'Number': 133,
  'id': 98},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'New Zealand',
  'Number': 2,
  'id': 99},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Nicaragua',
  'Number': 8,
  'id': 100},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Nigeria',
  'Number': 17,
  'id': 101},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Norway',
  'Number': 24,
  'id': 102},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Oman',
  'Number': 0,
  'id': 103},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Pakistan',
  'Number': 1243,
  'id': 104},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Palestinian territories',
  'Number': 1,
  'id': 105},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Panama',
  'Number': 14,
  'id': 106},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Paraguay',
  'Number': 29,
  'id': 107},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Peru',
  'Number': 82,
  'id': 108},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Philippines',
  'Number': 338,
  'id': 109},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Poland',
  'Number': 75,
  'id': 110},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Portugal',
  'Number': 120,
  'id': 111},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Qatar',
  'Number': 0,
  'id': 112},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Romania',
  'Number': 142,
  'id': 113},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Russia',
  'Number': 166,
  'id': 114},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Rwanda',
  'Number': 0,
  'id': 115},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Saint Kitts and Nevis',
  'Number': 0,
  'id': 116},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Saudi Arabia',
  'Number': 7,
  'id': 117},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Senegal',
  'Number': 25,
  'id': 118},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Serbia',
  'Number': 16,
  'id': 119},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Seychelles',
  'Number': 1,
  'id': 120},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Sierra Leone',
  'Number': 0,
  'id': 121},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Singapore',
  'Number': 4,
  'id': 122},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Slovakia',
  'Number': 7,
  'id': 123},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Slovenia',
  'Number': 11,
  'id': 124},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Somalia',
  'Number': 0,
  'id': 125},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'South Africa',
  'Number': 9,
  'id': 126},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'South Korea',
  'Number': 37,
  'id': 127},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Spain',
  'Number': 2827,
  'id': 128},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Sri Lanka',
  'Number': 0,
  'id': 129},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Sudan',
  'Number': 1,
  'id': 130},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Swaziland',
  'Number': 0,
  'id': 131},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Sweden',
  'Number': 112,
  'id': 132},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Switzerland',
  'Number': 34,
  'id': 133},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Syria',
  'Number': 71,
  'id': 134},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Taiwan',
  'Number': 0,
  'id': 135},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Tanzania',
  'Number': 2,
  'id': 136},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Thailand',
  'Number': 2,
  'id': 137},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Togo',
  'Number': 0,
  'id': 138},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Trinidad and Tobago',
  'Number': 0,
  'id': 139},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Tunisia',
  'Number': 4,
  'id': 140},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Turkey',
  'Number': 56,
  'id': 141},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Turkmenistan',
  'Number': 0,
  'id': 142},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Uganda',
  'Number': 0,
  'id': 143},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Ukraine',
  'Number': 116,
  'id': 144},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'United Kingdom',
  'Number': 292,
  'id': 145},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'United States',
  'Number': 201,
  'id': 146},
 {'Year': '2015',
  'District Code': '1',
  'District Name': 'Ciutat Vella',
  'Nationality': 'Uruguay',
  'Number': 32,
  'id': 147},

In [34]:
year="2017"
district="Ciutat Vella"
for x in inm_nat_clean:
    res = list(x.find({"Year":year}).find({"District Name":district}))
    print(res)

AttributeError: 'dict' object has no attribute 'find'

In [37]:
x = inm_nat.insert_many(inm_nat_clean)